name = "mapkitjs-dev"
type = "webpack"
account_id = "8ced7ddfa7e31ea36e901e98ff23188b"
zone_id = "da4b407824a3bd732e75bfc5e1d2711e"
vars = {KEY_ID = "G76D7DXT9W", TEAM_ID = "JVD8WT99LB"}
workers_dev = true

[env.production]
name = "mapkitjs"
vars = {KEY_ID = "G76D7DXT9W", TEAM_ID = "JVD8WT99LB"}
routes = [
  "mapkitjs.kytse.com",
  "mapkitjs.kytse.com/services/jwt"
]
